### ISSUE TITLE
Bugs in EndAuction

### ISSUE THREAD

**Issue by naterush** [aarondr77/AuctionHouse-Ethereum#9]
Three issues with this, I think.

First, on line [103](https://github.com/aarondr77/AuctionHouse-Ethereum/blob/master/Smart%20Contract#L103), you try and use variable minimumBid. However, this is a mapping and needs to be indexed into w/ auctionID. 

Also, in the case that highestBid < minimumBid, then the bid is locked in the contract for the rest of time. Consider, instead, enforcing this invariant in the Bid function (require (msg.value >= minimumBid[auctionID];).

Finally, you try and transfer money to your newly created Escrow contract. As previously noted, to do this, you need to first declare the unnamed function as payable.

**Comment by aarondr77** [comment]
I believe that this invariant is already taken care of in the bid function. The reason for the if statement here is that if no bid was made, then I don't want to open an escrow account. Therefore, no funds will get trapped in the contract, because if a bid is ever made, then the if statement will evaluate to true.

**Comment by naterush** [comment]
Good call. Sorry about that.

Maybe remove the check in this function, then?
